lindb/lindb

- pkg/bufioutil/bufio_reader.go
- pkg/bufioutil/bufio_reader_test.go
- pkg/bufioutil/bufio_writer.go
- pkg/bufioutil/bufio_writer_test.go
- pkg/bufioutil/pool_test.go
- remove truncate(), open read_only
- add size() to get the size of the underlying file
- pool is unnecessary, but still exported
> [fix:#10][pkg:bufioutil]: pool is unnecessary for bufioReader

- Makefile
- go.mod
- go.sum
- kv/flusher.go
- pkg/encoding/tsd.go
- tsdb/index/index.go
- tsdb/memdb/block_store.go
- tsdb/memdb/database.go
- tsdb/memdb/database_test.go
- tsdb/memdb/field_store.go
- tsdb/memdb/field_store_test.go
- tsdb/memdb/helper_test.go
- tsdb/memdb/metric_store.go
- tsdb/memdb/metric_store_test.go
- tsdb/memdb/pool.go
- tsdb/memdb/pool_test.go
- tsdb/memdb/segment_store.go
- tsdb/memdb/timeseries_store.go
- tsdb/memdb/timeseries_store_test.go
- tsdb/metrictbl/reader.go
- tsdb/metrictbl/reader_test.go
- tsdb/metrictbl/writer.go
- tsdb/metrictbl/writer_test.go
- vendor/github.com/golang/mock/gomock/call.go
- vendor/github.com/golang/mock/gomock/controller.go
- vendor/github.com/golang/mock/gomock/matchers.go
- vendor/modules.txt
- update gomock version
- fix mock
- remove hash-number-key in memdb
> [fix:#22][tsdb:memdb]: replace key from hash-number to string

- constants/coordinator.go
- coordinator/discovery/registry.go
- coordinator/discovery/registry_test.go
- coordinator/replica/status_state_machine.go
- coordinator/replica/status_state_machine_test.go
- coordinator/storage/cluster.go
- coordinator/task/executor.go
- coordinator/task/task_test.go
- models/node.go
- models/relicator.go
- models/state.go
- models/user.go
- pkg/pathutil/coordinator.go
- pkg/pathutil/coordinator_test.go
- pkg/state/repository.go
- sql/stmt/expr.go
- storage/runtime_test.go
1. discovery replica state of each broker
2. choose queryable storage node and shard ids for database
> [feat:#108][coordinator:replica]: replica state of database for broke query

- pkg/logger/logger.go
- pkg/logger/logger_test.go
> new format
- [2019-08-16 - 17:46:30]	[info]	[standalone]: etcd server is ready
- [2019-08-16 - 17:46:30]	[info]	[state]: new etcd client successfully	{"endpoints": ["http://localhost:2379"]}
- [2019-08-16 - 17:46:30]	[info]	[state]: new etcd client successfully	{"endpoints": ["http://localhost:2379"]}
- [2019-08-16 - 17:46:30]	[info]	[storage/runtime]: start storage state repository successfully
- [2019-08-16 - 17:46:30]	[info]	[storage/task/executor]: task executor started
> old format
- 2019-08-16T17:49:40.339+0800	info	[standalone]:etcd server is ready
- 2019-08-16T17:49:40.341+0800	info	[state]:new etcd client successfully	{"endpoints": ["http://localhost:2379"]}
- 2019-08-16T17:49:40.355+0800	info	[state]:new etcd client successfully	{"endpoints": ["http://localhost:2379"]}
- …
> [feat][pkg:logger]: optimize zap log format

- pkg/stream/binary.go
- pkg/stream/binary_test.go
- query/series_search_test.go
- query/storage_plan_test.go
- tsdb/doc.go
- tsdb/indexdb/database.go
- tsdb/indexdb/database_test.go
- tsdb/indexdb/interface.go
- tsdb/indextbl/rank_select.go
- tsdb/indextbl/series_flusher.go
- tsdb/indextbl/series_flusher_test.go
- tsdb/indextbl/series_reader.go
- tsdb/indextbl/series_reader_test.go
- tsdb/indextbl/series_trie_tree.go
- tsdb/indextbl/series_trie_tree_test.go
- tsdb/memdb/constants.go
- tsdb/memdb/database.go
- tsdb/memdb/database_test.go
- tsdb/memdb/metric_store.go
- tsdb/memdb/metric_store_index.go
- tsdb/memdb/metric_store_index_test.go
- tsdb/memdb/metric_store_test.go
- tsdb/memdb/segment_store.go
- tsdb/memdb/timeseries_store.go
- tsdb/memdb/timeseries_store_test.go
- tsdb/series/error.go
- tsdb/series/interface.go
- tsdb/series/multi_ver.go
- tsdb/series/multi_ver_test.go
- support querying from index table, such as series.Filter( FindSeriesIDsByExpr and GetSeriesIDsForTag), this is the capacities of inverted index;
- deserialization free trie-tree range query by rank-select ;
- forward index of index will be implemented in next PR.
-  `regex-expression filter` of series.Filter and `series.MetaGetter` is related to  forward index, so those two functions are still in development;
- remove time-range of tStore,  timeRange will be ignored during filtering from memdb
- fix evicted tStore allocated different seriesID when generated again;
> [feat:#170][tsdb]: add series reader to support series.Filter

- config/logging.go
- constants/tsdb.go
- pkg/field/iterator.go
- pkg/logger/logger_test.go
- pkg/logger/setting.go
- tsdb/doc.go
- tsdb/indexdb/database.go
- tsdb/indexdb/database_test.go
- tsdb/indexdb/interface.go
- tsdb/memdb/database.go
- tsdb/memdb/database_test.go
- tsdb/memdb/metric_store.go
- tsdb/memdb/metric_store_index.go
- tsdb/memdb/metric_store_index_test.go
- tsdb/memdb/metric_store_test.go
- tsdb/series/interface.go
- tsdb/tblstore/inverted_index_reader.go
- tsdb/tblstore/inverted_index_reader_test.go
- tsdb/tblstore/metrics_meta_reader.go
- tsdb/tblstore/metrics_meta_reader_test.go
- tsdb/tblstore/series_trie_tree.go
- tsdb/tblstore/series_trie_tree_test.go
- add suggest methods for both memdb and indexdb: suggestMetrics based on art-tree, suggestTags based on index-meta table, suggestTagValues based on inverted index table;
- implement series.MetaGetter for memdb
- add benchmarks for on-disk trie-tree search
- optimize the performance of regex-search, the literal string of regex-pattern is regarded as prefix-search now
- remove `json` log format as it looks weird
> [feat:#191][tsdb]: add suggest metrics

- kv/version/edit_log.go
- pkg/encoding/tsd.go
- pkg/stream/reader.go
- pkg/stream/stream_test.go
- series/version.go
- series/version_test.go
- storage/handler/writer.go
- tsdb/doc.go
- tsdb/memdb/metric_store.go
- tsdb/memdb/metric_store_test.go
- tsdb/tblstore/forward_index_flusher.go
- tsdb/tblstore/forward_index_merger.go
- tsdb/tblstore/forward_index_reader.go
- tsdb/tblstore/inverted_index_flusher.go
- tsdb/tblstore/inverted_index_flusher_test.go
- tsdb/tblstore/inverted_index_merger.go
- tsdb/tblstore/inverted_index_merger_test.go
- tsdb/tblstore/inverted_index_reader.go
- tsdb/tblstore/inverted_index_reader_test.go
- tsdb/tblstore/metrics_meta_reader.go
- tsdb/tblstore/metrics_nameid_merger.go
- tsdb/tblstore/metrics_nameid_reader.go
- tsdb/tblstore/series_trie_tree.go
- tsdb/tblstore/series_trie_tree_test.go
- add merger for InvertedIndexTable;
- use `deltaBitPacking` offsets to record tagValueBlock's positions in InvertedIndexTable;
- add `stream.ReadSlice` for zero-copy reading and arbitrarily jump-reading;
- add `stream.SeekStart` to re-read the slice without calling `Reset`;
- add a reusable `TrieTreeIterator` for filtering and prefix-searching of the trie-tree;
- move `versionBlocksMap` of `forwardIndexMerger` from heap to stack;
> [feat:#194][tsdb:tblstore]: merger of InvertedIndexTable

- storage/runtime.go
- tsdb/memdb/database.go
- tsdb/memdb/database_test.go
- tsdb/memdb/metric_store.go
- tsdb/memdb/metric_store_index.go
- tsdb/memdb/metric_store_scan_test.go
- tsdb/memdb/metric_store_test.go
precondition for memory-based flushing strategy
- adjust memory statistics granularity from metric-store to memdb
> [feat:#235]: memory statistics of memdb

- config/general.go
- monitoring/runtime_collector_test.go
- monitoring/system_test.go
- parallel/task_handler.go
- parallel/task_handler_test.go
- pkg/concurrent/model.go
- pkg/concurrent/pool.go
- pkg/concurrent/pool_test.go
- query/scan_worker.go
- query/scan_worker_test.go
- query/storage_executor.go
- tsdb/database.go
- New a concurrent-pool with idle-timeout config;
- add a SubmitAndWait method for blocking executing task
- remove capacity for the tasks channel, as it's parameter is useless; 
- add a Statistics for the concurrent-pool
> [feat][pkg:concurrent]: add a recyclable concurrent pool

- broker/api/admin/database_flusher.go
- broker/api/admin/database_flusher_test.go
- broker/runtime.go
- constants/coordinator.go
- coordinator/context/master.go
- coordinator/master.go
- coordinator/master_test.go
- coordinator/storage/cluster.go
- coordinator/storage/cluster_test.go
- coordinator/storage/database_flusher_task.go
- coordinator/storage/database_flusher_task_test.go
- coordinator/storage/task_executor.go
- mock/http_handle.go
- models/task.go
- models/task_test.go
- service/storage.go
- service/storage_test.go
- tsdb/engine.go
- tsdb/engine_test.go
- add http api in broker side
- master submit flush task
- storage node execute flush task that flushes the memory database's data
> [feat][coordinator]: flush memory database api for submit coordinator flush task

- tsdb/tblstore/invertedindex/flusher.go
- tsdb/tblstore/invertedindex/merger.go
- tsdb/tblstore/invertedindex/reader.go
- tsdb/tblstore/invertedindex/reader_test.go
- tsdb/tblstore/invertedindex/series_trie_tree.go
- tsdb/tblstore/invertedindex/series_trie_tree_test.go
- tsdb/tblstore/invertedindex/tagkv_entryset.go
- switch offsets block to FixedOffsets;
- add WalkTagValues method;
WalkTagValues walks each tag value and bitmap via fn.
If fn returns false, the iteration is stopped.
The values are the raw byte slices and not the converted types.
WalkTagValues(
tagID uint32,
tagValuePrefix string,
fn func(tagValue []byte, dataIterator tagValueIterator) bool,
) error
- improve TrieTreeIterator's speed by 10%;
- add tagValueIterator for lazily iterating tagValue's bitmap data;
> [feat][tsdb]: support WalkTagValues on inverted-index

- parallel/storage_query_flow_test.go
- query/storage_executor.go
- query/storage_executor_test.go
- series/interface.go
- tsdb/indexdb/index_database.go
- tsdb/indexdb/index_database_test.go
- tsdb/memdb/database.go
- tsdb/memdb/database_test.go
- tsdb/memdb/metric_store.go
- tsdb/memdb/metric_store_index.go
- tsdb/memdb/metric_store_index_test.go
- tsdb/memdb/metric_store_test.go
- get metric level all series ids by one tag key which has min tag value count
- scan the data
> [feat][query]: scan all metric data from memory database without query filter

- pkg/encoding/fixed_offset.go
- pkg/encoding/fixed_offset_test.go
- tsdb/indexdb/index_database.go
- tsdb/indexdb/index_database_test.go
- tsdb/metadb/id_sequencer.go
- tsdb/metadb/id_sequencer_test.go
- tsdb/metadb/interface.go
- tsdb/tblstore/invertedindex/reader.go
- tsdb/tblstore/invertedindex/reader_test.go
- tsdb/tblstore/invertedindex/tagkv_entryset.go
- tsdb/tblstore/invertedindex/tagkv_entryset_test.go
- tsdb/tblstore/metricsmeta/reader.go
- tsdb/tblstore/metricsmeta/reader_test.go
- load all tag key ids 
- get all series id by tag key id which has min tag values
- scan all metric data
> [feat][query]: scan all metric data from data family without query filter

- broker/api/router.go
- coordinator/replica/replicator_state_machine.go
- coordinator/replica/replicator_state_machine_test.go
- coordinator/state_machine_factory_test.go
- parallel/context.go
- parallel/context_test.go
- query/broker_executor.go
- replication/channel_manager.go
- replication/channel_manager_test.go
- fix replicator state is empty when create new database
- fix metric query nil point panic when broker execute err, query statement is nil
> [bug]: fix replicator state is empty when create new database

- constants/errors.go
- tsdb/indexdb/event.go
- tsdb/indexdb/event_test.go
- tsdb/indexdb/id_mapping_backend.go
- tsdb/indexdb/id_mapping_backend_test.go
- tsdb/indexdb/memory_database.go
- tsdb/indexdb/metric_id_mapping.go
- tsdb/indexdb/metric_id_mapping_test.go
- tsdb/metadb/metadata_backend.go
- tsdb/metadb/metadata_backend_test.go
- impl tags hash => series id backend storage for metric level
> [feat:#307][metadb]: impl id mapping backend storage using bbolt

- Makefile
- standalone/runtime.go
- disable etcd runtime log output, otherwise it will destroy the lind's logger format;
- gomock works well now, therefore the sed scripts is superfluous;
- go generate with displaying process rate
> [fix]: set embedded etcd runtime's logger level to error

- tsdb/tblstore/metricsdata/field_reader.go
- tsdb/tblstore/metricsdata/field_reader_test.go
- tsdb/tblstore/metricsdata/series_merger.go
- tsdb/tblstore/metricsdata/series_merger_test.go
- miss reset field reader context for reusing
- maybe field data not exist in current series merge context, but exist in pervious merge context, some field data will read duplicate
> [bug]: fix get wrong data after data compact completed

- app/broker/runtime.go
- app/broker/runtime_test.go
- app/standalone/runtime.go
- app/standalone/runtime_test.go
- app/storage/runtime.go
- constants/coordinator.go
- constants/coordinator_test.go
- coordinator/discovery/registry.go
- coordinator/discovery/registry_test.go
- coordinator/elect/election.go
- coordinator/master_controller.go
- coordinator/master_controller_test.go
- internal/bootstrap/cluster_initializer.go
- monitoring/native_pusher.go
- pkg/http/http_server.go
get wrong alive node when broker startup, because maybe master elect not complete.
> [bug]: fix watch wrong alive node when broker startup(master elect not complete)

- pkg/queue/consumer_group.go
- pkg/queue/consumer_group_test.go
- pkg/queue/queue.go
- pkg/queue/queue_test.go
- replica/replicator_local.go
- replica/replicator_local_test.go
- replica/replicator_peer.go
- reset replica index use ack index when data family data lost;
- reset consume group ack use ack of queue when consume group ack lost;
> [bug]: reset ack/replica index when lost data or consume group ack

- app/broker/runtime.go
- app/broker/runtime_test.go
Issue Number: #892 
- de-register broker node when server shutdown
Tests
> [enhance]: de-register broker node when shutdown

- query/task_manager.go
- query/task_manager_test.go
Issue Number: #878 
- fix alive/create/expire task metric no data
Tests
> [bug]: fix alive/create/expire task metric no data

- app/broker/api/exec/execute.go
- app/broker/api/exec/execute_test.go
Issue Number: #924 
fix nil point error when parse wrong sql.
rc: current parse sql not throw error
Tests
> [bug]: fix nil point when parse wrong sql

- Dockerfile
- Makefile
Issue Number:  not created yet
support release with a docker image.
Maybe we should create an official repo.  @stone1100 
```
$ make docker-build
docker build -t wangguohao/lindb:v0.2.1 --build-arg LD_FLAGS=-ldflags="-s -w -X github.com/lindb/lindb/config.Version=v0.2.1 -X github.com/lindb/lindb/config.BuildTime=2023-03-09T11:22:11+0800" .
[+] Building 91.8s (39/43)
[+] Building 91.9s (39/43)
[+] Building 92.4s (39/43)
[+] Building 92.8s (39/43)
[+] Building 134.4s (41/43)
[+] Building 158.1s (44/44) FINISHED
=> [internal] load build definition from Dockerfile                                                                                                                                           0.1s
=> => transferring dockerfile: 37B …
```
> [feat]: support release with a docker image

- pkg/http/middleware/access_log.go
- pkg/http/middleware/access_log_test.go
Issue Number: #932 
print error message in access log when handle http request failure
Tests
> [opt]: print error message when handle http request failure

- tsdb/data_family.go
- tsdb/data_family_test.go
Issue Number: #945 
if rollup interval < memory database TTL, using rollup interval to check if need to flush 
Tests
> [enhance]: need to check rollup Interval when memory database refreshing

- aggregation/series_agg.go
- pkg/option/tsdb.go
- pkg/option/tsdb_test.go
Issue Number: #938 
- check database's rollup intervals if valid
Tests
> [enhance]: check database's intervals if valid

- pkg/queue/consumer_group.go
- pkg/queue/consumer_group_test.go
- pkg/queue/fanout_queue_test.go
- pkg/queue/queue.go
- pkg/queue/queue_test.go
- replica/partition_test.go
- replica/replicator.go
- replica/replicator_peer.go
- replica/replicator_peer_test.go
- replica/replicator_test.go
- remove sleep logic when cannot consume wal data
- wait strategy based on sync.Condition
Issue Number: #959 
Tests
> [enhance]: consume group wait strategy when WAL is empty

- cmd/cli/main.go
- internal/client/execute.go
- query/search.go
Issue Number: #991 
1. Always return empty value instead of nil when querying metadata.
2. Modify the color of the input sql and add the recover function.
Tests
> [bug]: fix nil metadata and refactor lindcli

- query/operator/tag_values_lookup.go
Issue Number: #994 
Fixing the issue where the NOT IN statement returns an empty result when the tag value does not exist.
Tests
> [bug:#994]: fix not in statement returns an empty result

- app/broker/api/exec/command/schema.go
- constants/errors.go
- replica/partition.go
- replica/partition_test.go
- replica/replicator_remote.go
Issue Number: #1017
storage will panic when write old data point.
Rootcause:
- broker not filter old data point, because database not set default write acceptable time range.
- storage close wal log
Tests
> [bug]: fix storage panic when write old data point
