lindb/lindb

CONTRIBUTING.md, README.md
#3 
define contributing workflow
=> add contributing workflow

coordinator/database/shard_assign.go, coordinator/database/shard_assign_test.go, pkg/option/database.go
- add shard assignment reference kafka partition assignment
=> [feat:eleme#18][coordinator:shard_assign]: shard assigns replica list for database creation

coordinator/discovery/discovery.go, coordinator/discovery/discovery_test.go, coordinator/discovery/register.go, coordinator/discovery/register_test.go, coordinator/elect/election.go, coordinator/elect/eletcion_test.go, pkg/state/etcd.go, pkg/state/etcd_test.go, pkg/state/heartbeat.go, pkg/state/repository.go
master elect and node discovery
=> [feat:eleme#36][coordinator:elect]: master elect based on etcd

go.sum, pkg/logger/logger.go, replication/channel.go, replication/channel_test.go, replication/replicator.go, replication/replicator_test.go, replication/sequence.go, rpc/pb/storage.proto, rpc/proto/broker/broker.pb.go, rpc/proto/common/common.pb.go, rpc/proto/field/field.pb.go, rpc/proto/storage/storage.pb.go, rpc/rpc.go, rpc/rpc_test.go, storage/handler/write_test.go, storage/handler/writer.go, vendor/modules.txt
fix broker, storage replication sequence problem
=> [feat:#1][replication:replication]fix replicaion seq problem

tsdb/diskdb/id_sequencer.go, tsdb/diskdb/id_sequencer_test.go, tsdb/diskdb/index_database.go, tsdb/diskdb/index_database_test.go, tsdb/diskdb/interface.go, tsdb/doc.go, tsdb/memdb/helper_test.go, tsdb/memdb/metric_store.go, tsdb/memdb/metric_store_index.go, tsdb/tblstore/inverted_index_reader.go, tsdb/tblstore/inverted_index_reader_test.go, tsdb/tblstore/metrics_meta_flusher.go, tsdb/tblstore/metrics_meta_merger.go, tsdb/tblstore/metrics_meta_merger_test.go, tsdb/tblstore/metrics_meta_reader.go, tsdb/tblstore/metrics_meta_reader_test.go, tsdb/tblstore/metrics_nameid_flusher.go, tsdb/tblstore/metrics_nameid_merger.go, tsdb/tblstore/metrics_nameid_merger_test.go, tsdb/tblstore/metrics_nameid_reader.go, tsdb/tblstore/metrics_nameid_reader_test.go
- rename tagID to tagKeyID
- add merger for metric-meta-table
=> [feat:#194][tsdb:tblstore]: merger of MetricMetaTable

broker/handler/tcp_handler_test.go
1. avoid establish real connection
2. test handler handler function
=> [fix:#84][broker/tcp_handler]: fix test failed bugs

go.mod, go.sum, models/tag.go, models/tag_test.go, replication/channel.go, tsdb/memdb/database.go, tsdb/memdb/database_test.go, tsdb/memdb/metric_store_index.go, tsdb/memdb/metric_store_index_test.go, tsdb/memdb/timeseries_store.go, vendor/github.com/cespare/xxhash/LICENSE.txt, vendor/github.com/cespare/xxhash/README.md, vendor/github.com/cespare/xxhash/go.mod, vendor/github.com/cespare/xxhash/go.sum, vendor/github.com/cespare/xxhash/rotate.go, vendor/github.com/cespare/xxhash/rotate19.go, vendor/github.com/cespare/xxhash/xxhash.go, vendor/github.com/cespare/xxhash/xxhash_amd64.go, vendor/github.com/cespare/xxhash/xxhash_amd64.s, vendor/github.com/cespare/xxhash/xxhash_other.go, vendor/github.com/cespare/xxhash/xxhash_safe.go, vendor/github.com/cespare/xxhash/xxhash_unsafe.go, vendor/github.com/plar/go-adaptive-radix-tree/tree_traversal.go, vendor/modules.txt
See: http://cyan4973.github.io/xxHash/
=> [feat]: replace fnv-1a with xxhash

aggregation/expression.go, aggregation/expression_test.go, aggregation/field_agg.go, aggregation/field_agg_test.go, aggregation/field_iterator.go, aggregation/field_iterator_test.go, aggregation/function/type.go, aggregation/function/type_test.go, aggregation/group_agg.go, aggregation/group_agg_test.go, aggregation/grouped_iterator.go, aggregation/grouped_iterator_test.go, aggregation/helper_test.go, aggregation/primitive_agg.go, aggregation/primitive_agg_test.go, aggregation/series_agg.go, parallel/intermediate.go, parallel/job_manager.go, parallel/result_merger.go, parallel/result_merger_test.go, query/scan_worker.go, query/scan_worker_test.go, query/storage_executor.go, series/field/schema.go, series/field/schema_test.go, series/field/type.go, series/field/type_test.go, tsdb/memdb/metric_scan_event.go, tsdb/memdb/metric_scan_event_test.go
- modify some unit test logic
- fix memory database scan UT bug
- add summary field schema
=> [feat][query]: optimize query performance issue/modify UT

web/src/components/BreadcrumbHeader.tsx, web/src/components/Chart/ViewBoard.tsx, web/src/components/Layout/SiderMenu.tsx, web/src/model/Breadcrumb.ts, web/src/store/BreadcrumbStore.ts, web/src/store/ChartStore.ts, web/src/store/StoreManager.ts
modify the datasource of breadcrumb and refactor the SiderMenu component to fit new BreadcrumbHeader component
=> [feat:#273][fe]: refactor BreadcrumbHeader component to support dynamic breadcrumb navigation

monitoring/system_collector_test.go, monitoring/system_test.go, tsdb/memdb/constants.go, tsdb/memdb/database.go, tsdb/memdb/database_test.go, tsdb/memdb/metric_bucket.go, tsdb/memdb/metric_bucket_test.go
1. metric name convert hash code
2. store hash code => metric id mapping
3. using bitmap + slice store metric id => metric store mapping
=> [refactor][memdb]: metric name => metric store mapping

parallel/storage_query_flow_test.go, tsdb/field/aggregate.go, tsdb/field/aggregate_test.go, tsdb/tblstore/metricsdata/filter.go, tsdb/tblstore/metricsdata/filter_test.go
- add aggregate method for reading field data by field type
=> [feat][query]: read/aggregate field data from sst file based on field type

replication/chunk.go, web/src/containers/Setting/NewDatabase.tsx, web/src/service/Storage.ts
- fix snappy compress wrong data, because reuse bytes.Buffer
- fix fe create database config bug
=> [bug]: fix snappy compress data error

aggregation/function/type.go, aggregation/function/type_test.go, broker/api/metric/write.go, series/field/agg_func.go, series/field/agg_func_test.go, series/field/schema.go, series/field/schema_test.go, series/field/type.go, series/field/type_test.go, tsdb/memdb/field_store.go, tsdb/memdb/field_type.go, tsdb/memdb/metric_store.go, tsdb/memdb/timeseries_store_test.go, tsdb/query/aggregate.go
- implements gauge field(both read/write)
- fix flush tag key inverted index bug, need keep in order by tag key id
=> [feat]: impl gauge field write/read

aggregation/expression.go, aggregation/field_agg.go, aggregation/fields/field.go, aggregation/function/functions.go, aggregation/function/functions_test.go, series/field/func_params.go, series/field/schema.go, series/field/schema_test.go, series/field/type.go
- impl function call need based on primitive fields meta which defines in field schema
=> [feat][expression]: impl avg function based on primitive fields meta

pkg/queue/fanout.go, pkg/queue/fanout_test.go
remove fanout meta to avoid influence of the previous run of test
=> [fix][pkg/queue]: fix test bug

query/metadata_storage_executor.go, query/metadata_storage_executor_test.go, tsdb/indexdb/index_database.go, tsdb/metadb/interface.go, tsdb/metadb/metedata_database.go, tsdb/metadb/tag_metadata.go
尝试实现了SuggestMetric、SuggestTagKey、SuggestTagValue
ps: 其中namespace没有作为请求参数传入，目前使用default值进行操作
=> [query]: impl Suggest api:SuggestMetric、SuggestTagKey、SuggestTagValue

coordinator/database/admin_state_machine.go, coordinator/database/shard_assign.go, coordinator/database/shard_assign_test.go
note: only implement increase shards number
=> [tsdb]: impl modify shard assign

replication/shard_channel_test.go, tsdb/memdb/data_point_buffer.go, tsdb/memdb/data_point_buffer_test.go, tsdb/memdb/database.go, tsdb/memdb/database_test.go, tsdb/memdb/integration_test.go, tsdb/shard.go, tsdb/shard_test.go
- create local temp path(using millisecond) for memory cache 
- remove local temp path after memory database flush
=> [tsdb][memdb]: create temp disk storage for data points cache

tsdb/memdb/database.go, tsdb/memdb/database_test.go, tsdb/shard.go, tsdb/shard_test.go
- swap a new memory database for writing new data when does flush job
- waiting complete current writing in immutable memory database
=> [tsdb]: add immutable memory database for flushing data like lsm

README.md
**What changes are proposed ?**
Added build instructions to project README. This will be helpful for new starters on the project.
**How has the change been tested ?**
All commands provided were tested by me while building the project from scratch. Markdown tested on IDE markdown mode and on Github web portal's markdown view.
**Issue Link ?**
https://github.com/lindb/lindb/issues/376
=> [docs:#376]: add build instructions in project README

README.md
What changes are proposed ?
Adding instructions to access LinDB web interface.
How was the change tested ?
Markdown on IDE
Issue ?
#376
=> [docs:#376]: Add README instructions to access LinDB web interface

README.md
**What change is proposed ?**
Add stand alone mode deployment instructions in README. 
**How was the change tested ?**
IDE markdown.
**Link to issue ?**
None
=> [docs]: Add README instructions for deployment in standalone mode

pkg/queue/page/mpage.go, pkg/queue/page/mpage_test.go, tsdb/database.go, tsdb/database_test.go, tsdb/indexdb/id_mapping_backend.go, tsdb/indexdb/id_mapping_backend_test.go, tsdb/indexdb/index_database_test.go, tsdb/memdb/integration_test.go, tsdb/metadb/metadata.go, tsdb/metadb/metadata_backend.go, tsdb/metadb/metadata_backend_test.go, tsdb/metadb/metadata_test.go, tsdb/metadb/metedata_database.go, tsdb/metadb/metedata_database_test.go, tsdb/metadb/metric_metadata.go, tsdb/metadb/metric_metadata_test.go, tsdb/wal/base_wal.go, tsdb/wal/metric_meta_wal.go, tsdb/wal/metric_meta_wal_test.go, tsdb/wal/series_id_wal.go, tsdb/wal/series_id_wal_test.go
- add metric metadata wal when create new metricID/TagKeyID/FieldID
- recovery wal when system restart
- check recovery in period
=> [feat][tsdb]: add metric metadata wal

aggregation/expression.go, aggregation/field_agg.go, aggregation/field_iterator.go, aggregation/primitive_agg.go, aggregation/primitive_agg_test.go, aggregation/selector/slot.go, aggregation/series_agg.go, broker/api/metric/write.go, tsdb/memdb/timeseries_store.go, tsdb/memdb/timeseries_store_test.go, tsdb/tblstore/metricsdata/reader.go, tsdb/tblstore/metricsdata/reader_test.go
- fix flush need by family time
- fix loss last data point of data family when cross mutli data family
- fix loss last data point of finally result set
=> [bug]: fix get wrong data when search cross mutli data family

kv/table/reader.go, pkg/bufioutil/bufio_writer.go, tsdb/indexdb/index_database.go, tsdb/tblstore/invertedindex/base_reader.go, tsdb/tblstore/invertedindex/inverted_merger_test.go, tsdb/tblstore/invertedindex/inverted_reader.go
=> [bug]: fix panic when do index compact job

broker/api/state/storage.go, broker/api/state/storage_test.go, models/monitoring.go, monitoring/system.go, monitoring/system_collector.go, monitoring/system_collector_test.go, monitoring/system_test.go, tsdb/data_flush_checker.go, tsdb/data_flush_checker_test.go, web/src/config/monitoring/System.ts, web/src/containers/home/NodeInfo.tsx, web/src/model/Monitoring.ts
- add a network stat collector
=> [feat][monitoring]: add netstat metrics

coordinator/task/processor.go, kv/version/edit_log.go, kv/version/edit_log_test.go, kv/version/file_meta.go, kv/version/file_meta_test.go, kv/version/log.go, kv/version/log_test.go, kv/version/version_set.go, tsdb/data_flush_checker.go, tsdb/data_flush_checker_test.go, tsdb/database.go, tsdb/database_test.go, tsdb/engine.go, tsdb/engine_test.go
- impl flush database task by manual
- print edit log in log file
=> [feat][tsdb]: impl flush database task by api

standalone/initialize.go, standalone/initialize_test.go, standalone/runtime.go, standalone/runtime_test.go
- create default storage cluster
- create _internal database
=> [feat][standalone]: initialize storage cluster env

broker/api/query/metadata.go, broker/api/query/metadata_test.go, models/metadata.go, sql/stmt/constants.go, sql/stmt/expr.go, sql/stmt/metadata.go, sql/stmt/metadata_test.go, web/src/components/meta/DatabaseNames.tsx, web/src/components/meta/TagValues.tsx, web/src/config/config.ts, web/src/containers/query/MetricDataSearch.tsx, web/src/model/meta/Metadata.ts, web/src/service/Metadata.ts, web/src/service/metadata/MetadataService.ts, web/src/store/StoreManager.ts, web/src/store/admin/DatabaseStore.ts, web/src/store/metadata/MetadataStore.ts
- show namespace/measurement/field/tag key/tag value
=> [feat][ui]: impl metadata query var sql

aggregation/down_sampling_agg.go, constants/tsdb.go, pkg/timeutil/time_range.go, tsdb/tblstore/metricsdata/merger.go, tsdb/tblstore/metricsdata/series_merger.go, tsdb/tblstore/metricsdata/series_merger_test.go
* add down sampling aggregator
* rollup merge using down sampling aggreator
=> feat: add downsampling aggregator

app/standalone/runtime.go, app/storage/runtime.go, app/storage/runtime_test.go, constants/coordinator.go, coordinator/discovery/discovery.go, coordinator/master/state_manager.go, coordinator/master/storage_cluster.go, go.mod, go.sum
1. fix parse wrong stateful node id when node offline
2. fix panic when storage node online after master state manager closed
=> [bug]: fix parse wrong stateful node id when node offline

.github/dependabot.yml
=> 增加版本升级检查工具

.github/ISSUE_TEMPLATE/🐛-bug-report.md, .github/ISSUE_TEMPLATE/🚀-enhancement.md, .github/ISSUE_TEMPLATE/🚀-feature-request.md, .github/ISSUE_TEMPLATE/🤔-ask-a-question.md, .github/pull_request_template.md
Issue Number: close #xxx
add issue/pr template
Tests
=> [chore]: add issue/pr template

app/root/api/command/state.go, app/root/api/command/state_test.go, coordinator/root/state_manager.go, coordinator/root/state_manager_test.go, web/src/components/index.ts, web/src/components/state/BrokerView.tsx, web/src/components/state/StorageView.tsx, web/src/i18n/en_US.ts, web/src/i18n/zh_CN.ts, web/src/models/state.ts, web/src/pages/state/Overview.tsx
Issue Number: #883 
view broker cluster state in overview page
Tests
=> [feat]: view broker cluster state

app/broker/api/router.go, app/root/api/command/request.go, app/root/api/command/request_test.go, app/root/api/execute.go, app/root/api/router.go, app/storage/runtime.go, internal/api/config_handle.go, internal/api/config_handle_test.go, internal/api/env_handle.go, internal/api/env_handle_test.go, internal/api/explore_handle.go, internal/api/explore_handle_test.go, internal/api/log_handle.go, internal/api/log_handle_test.go, internal/api/request_handle.go, internal/api/request_handle_test.go, internal/client/request.go, internal/client/request_test.go, web/src/i18n/en_US.ts, web/src/i18n/zh_CN.ts, web/src/pages/monitoring/RequestView.tsx
Issue Number: #894 
- refactor view request command api
- view pending sql request for root
Tests
=> [enhance]: view pending sql request for root

coordinator/broker/state_manager.go, coordinator/broker/state_manager_test.go, coordinator/master/state_manager.go, coordinator/root/state_manager.go, coordinator/storage/state_manager.go, metrics/coordinator.go, metrics/coordinator_test.go, metrics/query.go, web/src/configs/dashboard.config.tsx, web/src/configs/index.ts, web/src/configs/monitoring/broker.coordinator.ts, web/src/configs/monitoring/query.ts, web/src/configs/monitoring/root.coordinator.ts, web/src/configs/monitoring/storage.coordinator.ts, web/src/constants/name.constants.ts, web/src/pages/monitoring/DashboardView.tsx
Issue Number: #878 
- refactor coordinator state manager metric
- root self-monitoring dashboard
Tests
=> [feat]: dashboard for root cluster

app/root/api/router.go, web/src/pages/monitoring/LogView.tsx
Issue Number: #895 
- view log files
Tests
=> [enhance]: log view support root cluster

internal/api/log_handle.go, internal/api/log_handle_test.go
Issue Number: #889 
Fixes security issue with directory traversal.
Tests
=> [bug]: fix directory traversal security issue

app/root/runtime.go, app/root/runtime_test.go, coordinator/discovery/registry.go, coordinator/discovery/registry_test.go
Issue Number: #883 
- fixed cannot discovery register root node when server startup
Tests
=> [bug]: fix cannot discovery register root node

web/src/pages/monitoring/LogView.tsx
Issue Number: #895 
- hide storage alive node select input
Tests
=> [enhance]: hide storage alive node under log view for root

Makefile, deploy.sh
- add ldflags -w -s(go build)
Tests
=> [chore]: go build with ldflag(s|w)

CHANGELOG/CHANGELOG-1.0.md
add change logs for v0.2.0
Tests
=> [chore]: add change log(v0.2.0)

README-zh_CN.md, README.md
Issue Number: #906
fix web console guide under readme
Tests
=> [bug]: fix web console guide

app/broker/deps/http_deps.go, app/broker/deps/http_deps_test.go, app/root/deps/http_deps.go
modify broker/root http read timeout config not working
Issue Number: #908 
Tests
=> [bug]: fix http read timeout not working

coordinator/discovery/event.go, coordinator/discovery/event_test.go, coordinator/discovery/state_machine.go, coordinator/discovery/state_machine_test.go, coordinator/master/state_machine_factory.go, coordinator/master/state_machine_factory_test.go, coordinator/master/state_manager.go, coordinator/master/state_manager_test.go, coordinator/master/storage_cluster.go, coordinator/master/storage_cluster_test.go, coordinator/master_controller_test.go, coordinator/storage/state_machine_factory.go, coordinator/storage/state_machine_factory_test.go, coordinator/storage/state_manager.go, coordinator/storage/state_manager_test.go, tsdb/database.go, tsdb/engine.go, tsdb/engine_test.go, tsdb/files.go, tsdb/functions.go
- master/storage: database limits coordinator
Tests
=> [feat]: database limits coordinator

config/config_test.go, config/standalone.toml.example, config/storage.go, config/storage.toml.example, constants/errors.go, e2e/tsdb/indexdb/index_database_test.go, ingestion/influx/parser_test.go, models/limits.go, models/limits_test.go, tsdb/database.go, tsdb/database_test.go, tsdb/engine.go, tsdb/engine_test.go, tsdb/indexdb/index_database.go, tsdb/indexdb/index_database_test.go, tsdb/indexdb/interface.go, tsdb/indexdb/metric_id_mapping.go, tsdb/indexdb/metric_id_mapping_test.go, tsdb/metadb/metric_metadata.go, tsdb/shard.go, tsdb/shard_test.go
- add metric series limit
Tests
=> [feat]: add metric series limit

constants/tsdb.go, models/limits.go, tsdb/metadb/interface.go, tsdb/metadb/metedata_database.go, tsdb/metadb/metedata_database_test.go, tsdb/metadb/metric_metadata.go, tsdb/metadb/metric_metadata_test.go, tsdb/shard.go, tsdb/shard_test.go
- add metric field limit
Tests
=> [feat]: add metric field limit

tsdb/indexdb/index_database.go, tsdb/indexdb/index_database_test.go, tsdb/indexdb/interface.go, tsdb/indexdb/inverted_index.go, tsdb/indexdb/inverted_index_test.go, tsdb/metadb/interface.go, tsdb/metadb/metedata_database.go, tsdb/metadb/metedata_database_test.go, tsdb/metadb/metric_metadata.go, tsdb/metadb/metric_metadata_test.go, tsdb/shard.go, tsdb/shard_test.go
=> [feat]: add metric tags limit

constants/errors.go, flow/context.go, query/operator/series_limit.go, query/operator/series_limit_test.go, query/stage/shard_scan_stage.go
- add series limit operator for metric query
Tests
=> [feat]: series limit operator

app/broker/api/ingest/write.go, ingestion/influx/parser.go, ingestion/influx/parser_test.go, models/limits.go, models/limits_test.go, query/operator/series_limit.go, query/operator/series_limit_test.go, series/metric/row_flat_decoder.go, series/metric/row_flat_decoder_test.go, series/metric/row_proto_converter.go, series/metric/row_proto_converter_test.go, tsdb/indexdb/metric_id_mapping.go, tsdb/indexdb/metric_id_mapping_test.go, tsdb/metadb/metric_metadata.go, tsdb/metadb/metric_metadata_test.go
- add disable database limit logic
Tests
=> [feat]: impl disable database limit

constants/errors.go, models/limits.go, tsdb/metadb/interface.go, tsdb/metadb/metadata_backend.go, tsdb/metadb/metadata_backend_test.go, tsdb/metadb/metedata_database.go, tsdb/metadb/metedata_database_test.go, tsdb/shard.go, tsdb/shard_test.go
max num. of namespace/metric limit
Tests
=> [feat]: max namespace/metric limit

app/broker/api/exec/execute.go, app/broker/api/router.go, app/broker/api/slow_sql.go, app/broker/api/slow_sql_test.go, cmd/lind/broker.go, cmd/lind/root.go, config/broker.go, config/broker.toml.example, config/standalone.toml.example, pkg/http/http_server.go, pkg/http/middleware/access_log.go, pkg/logger/logger.go, pkg/logger/logger_test.go, pkg/logger/setting.go, pkg/logger/setting_test.go
Issue Number: #881 
- fix http access log file not working
- add slow sql log file
Tests
=> [feat]: add slow sql log

web/src/components/common/SimpleStatusTip.tsx, web/src/components/common/StatusTip.tsx, web/src/hooks/use.metric.ts, web/src/utils/api.ts
Issue Number: #918 
- metric chart show error message if query fail
Tests
=> [enhance]: metric chart show error message if query fail

CHANGELOG/CHANGELOG-1.0.md
=> [chore]: add change log(v0.2.1)

config/broker.go, config/broker.toml.example, config/broker_test.go, config/general.go, config/global.go, config/global_test.go, config/logging.go, config/monitor.go, config/root.go, config/root.toml.example, config/root_test.go, config/standalone.go, config/standalone.toml.example, config/standalone_test.go, config/storage.go, config/storage.toml.example, config/storage_test.go, go.mod, go.sum
Issue Number: #928 
- read config from env
- env config overwrite file
Tests
=> [feat]: read config from env

web/src/components/common/TimePicker.tsx
- fix time picker no display last 30 days
Tests
=> [bug]: fix time picker no display last 30 days

app/broker/api/exec/command/schema.go, app/broker/api/exec/command/schema_test.go, coordinator/master/state_manager.go, coordinator/master/state_manager_test.go
Issue Number: #935 
fix can create database successfully when storage not exist
Tests
=> [bug]: cannot create database if storage not exist

Dockerfile
add Lindb cli tools to docker image
=> [opt]: add cli tools to docker image

aggregation/series_agg.go, aggregation/series_agg_test.go, kv/version/version_set_test.go, query/stage/data_load_stage.go
=> [bug]: got unexpected result when async load family data

kv/compact_job.go, kv/family_rollup.go, kv/family_rollup_test.go, kv/store_manager.go, kv/version/version_set.go, kv/version/version_set_test.go, tsdb/database.go, tsdb/interval_segment.go
=> [bug]: fix cannot rollup data for windows

CHANGELOG/CHANGELOG-1.0.md
=> [chore]: add change log(v0.2.2)

app/standalone/runtime_test.go, config/storage.go, e2e/tsdb/indexdb/index_database_test.go, pkg/fileutil/mmap_test.go, pkg/ltoml/io_test.go, pkg/queue/consumer_group_test.go, pkg/queue/fanout_queue.go, pkg/queue/fanout_queue_test.go, pkg/queue/queue_test.go, replica/channel_manager_test.go, replica/wal.go, replica/wal_test.go
=> [opt]: join file paths

.github/workflows/dockerhub-description.yml
=> [chore]: sync readme to docker hub

.github/workflows/dockerhub-description.yml, query/context/utils.go
get different aggregate result when use different group by interval, for explain group by(1m/5m/1h/none)
Tests
=> [bug]: fix get diff agg result using diff group by interval

.github/workflows/docker-release.yml, CHANGELOG/CHANGELOG-1.0.md
=> [chore]: add change log(v0.2.3)

.github/workflows/lind.yml
Use https://github.com/golangci/golangci-lint-action for better user experience.
Tests
=> [chore]: use golangci/golangci-lint-action

.github/workflows/release.yml, CHANGELOG/CHANGELOG-1.0.md, CHANGELOG/configuration.json, CHANGELOG/release_tpl.md
=> [chore]: add auto release github workflow

deploy.sh
Issue Number: #966 
fix no cpu stats data for darwin package
Tests
=> [bug]: darwin package no cpu stats data

.github/workflows/docker-release.yml, CHANGELOG/CHANGELOG-1.0.md, deploy.sh
=> [bug]: fix build darwin package fail

README-zh_CN.md, README.md, deploy.sh
add darwin arm64 package
Tests
=> [chore]: build darwin arm64 package

aggregation/binary.go, web/.stylelintrc.json, web/header.js, web/src/styles/theme/_palette.scss
=> [bug]: fix theme color palette setting

series/metric/row_flat_decoder.go
=> [bug]: use metric level namespace if set

.github/workflows/docker-latest.yml, .github/workflows/docker-release.yml, web/Makefile
=> [feat]: CI support arm64 images

.github/workflows/docker-latest.yml, .github/workflows/docker-release.yml, Dockerfile-gh, web/src/components/data/MetadataSelect.tsx, web/src/components/data/TagFilterSelect.tsx, web/src/pages/search/DataExplore.tsx
=> [bug]: fix data explore not support namespace

.github/pr-title-checker-config.json, .github/workflows/release.yml, Dockerfile, Dockerfile-gh
=> [chore]: upgrade go version for ci

query/context/root_metric_context.go, sql/calc.go, sql/calc_test.go, sql/listener.go, sql/query_stmt_parser.go, sql/query_stmt_parser_test.go, sql/stmt/binary_operator.go, sql/stmt/binary_operator_test.go, sql/stmt/query.go
Issue Number: #912 
> Let's implement scenario 2 first
Tests
=> [feat:#912]: support comparison binary operations

.github/workflows/lind.yml
=> [chore]: disable golangci-lint cache

.github/workflows/lind.yml, pkg/imap/int_map.go, tsdb/data_family.go, tsdb/data_family_test.go, tsdb/memdb/database.go, tsdb/memdb/database_test.go, tsdb/memdb/field_store.go, tsdb/memdb/field_store_test.go, tsdb/memdb/metric_store.go, tsdb/memdb/metric_store_test.go, tsdb/memdb/time_series_store.go
estimate heap size of memory database
Tests
=> [feat]: memory database estimate heap size

tsdb/memdb/data_loader.go, tsdb/memdb/metric_store_filter.go
=> [refactor]: memory database data loader

index/model/trie_bucket.go, index/model/trie_bucket_test.go
=> [bug:#1012]: fix show metrics returns incorrect results

.gitignore, Makefile, e2e/tsdb/database_test.go, metrics/tsdb.go, pkg/timeutil/time.go, pkg/timeutil/time_test.go, replica/wal.go, replica/wal_test.go, tsdb/data_family.go, tsdb/data_family_test.go, tsdb/data_segment.go, tsdb/data_segment_test.go, tsdb/database.go, tsdb/engine.go, tsdb/functions.go, tsdb/interval_data_segment.go, tsdb/interval_data_segment_test.go, tsdb/segment.go, tsdb/segment_partition.go, tsdb/segment_partition_test.go, tsdb/segment_test.go, tsdb/shard.go, tsdb/shard_test.go
=> [enhance:#1021]: monthly partitioning of indices

Dockerfile, Dockerfile-gh, internal/linmetric/histogram_delta.go, internal/linmetric/histogram_test.go
=> [bug]: fix build docker fail

.codecov.yml, go.mod, go.sum, prometheus/engine.go
=> [bug]: miss makezero in slice init

aggregation/expression.go, aggregation/fields/field.go, aggregation/function/quantile.go, aggregation/function/quantile_test.go, app/broker/api/ingest/write.go, pkg/collections/array_list.go, tsdb/memdb/database.go, tsdb/memdb/database_test.go
- ignore histogram bucket if count<0
- fix histogram no data found
Tests
=> [opt]: ignore histogram bucket if count<0

query/operator/metadata_lookup.go, series/field/metas.go, series/field/metas_test.go, tsdb/memdb/metric_store.go, tsdb/memdb/metric_store_filter.go, tsdb/tblstore/metricsdata/reader.go
=> [bug]: fix get wrong data from memory database

series/field/metas.go, tsdb/memdb/database.go, tsdb/memdb/database_test.go, tsdb/memdb/metric_store.go, tsdb/memdb/metric_store_test.go, web/package.json, web/vite.config.ts, web/yarn.lock
=> [opt]: opt metric field memory store

tsdb/memdb/compact_store.go, tsdb/memdb/compact_store_test.go, tsdb/memdb/data_point_buffer.go, tsdb/memdb/database.go, tsdb/memdb/database_test.go, tsdb/memdb/time_series_index.go
=> [feat]: memory database approximate memory size

tsdb/memdb/database.go, tsdb/memdb/database_test.go, tsdb/memdb/index_database.go, tsdb/memdb/index_database_test.go, tsdb/memdb/metadata_database.go, tsdb/memdb/metadata_database_test.go, tsdb/memdb/metric_store.go, tsdb/memdb/metric_store_test.go, tsdb/memdb/time_series_index.go, tsdb/memdb/time_series_index_test.go
=> [feat]: cleanup memory metric meta/index if not used

pkg/queue/consumer_group.go, replica/replicator_local.go, replica/replicator_remote.go
=> [bug]: fix wal ack invalid seq msg

README-ja.md, README-zh_CN.md, README.md
I created Japanese translated README.
=> [docs]: add Japanese README file

.github/workflows/release.yml
=> [enhance]: remove installation guides from release notes

tsdb/memdb/index_database.go, tsdb/memdb/metadata_database.go
=> [bug]: fix cannot flush metric data when server shutdown
